name: Beta Stossycord build
on: [push, pull_request]

jobs:
  build:
    name: Build and upload Stossycord Beta
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-13'
            version: '15.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Verify Swift version
        run: swift --version

      - name: Build Stossycord
        run: make build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Convert to IPA
        run: make ipa

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%c')" >> $GITHUB_OUTPUT

      - name: Get current date in AltStore date form
        id: date_altstore
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload to new beta release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref_name }}
          draft: true
          prerelease: true
          files: SideStore.ipa
          body: |

      - name: Add version to IPA file name
        run: mv SideStore.ipa SideStore-${{ steps.version.outputs.version }}.ipa

      - name: Upload Stossycord.ipa Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Stossycord.ipa
          path: Stossycord.ipa

      - name: Upload *.dSYM Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Stossycord-dSYM
          path: ./*.dSYM/
