name: iOS Build

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Stossyfork
    runs-on: macos-26

    env:
      DERIVED_DATA_PATH: ${{ runner.temp }}/DerivedData

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Cache SwiftPM dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ${{ env.DERIVED_DATA_PATH }}
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve Swift packages
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project Stossycord.xcodeproj \
            -scheme Stossycord \
            -derivedDataPath "$DERIVED_DATA_PATH"

      - name: Build (iOS Simulator)
        run: |
          xcodebuild \
            -project Stossycord.xcodeproj \
            -scheme Stossycord \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Compress build products
        if: success()
        run: |
          mkdir -p artifacts
          ditto -c -k --sequesterRsrc --keepParent "$DERIVED_DATA_PATH/Build/Products" artifacts/BuildProducts.zip

      - name: Upload build products
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Stossycord-BuildProducts
          path: artifacts/BuildProducts.zip
          if-no-files-found: error
